server:
    port: 8080
    servlet:
      context-path: /ins
spring:
    h2:
       console:
            enabled: true
            path: /h2console
    profiles: local, default

datasource:
    sampleapp:
      url: jdbc:h2:~/test
      username: sa
      password:
      driverClassName: org.h2.Driver
      defaultSchema:
      maxPoolSize: 10
      initialization-mode: embedded
      hibernate:
        hbm2ddl.method: create
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
---



server:
    port: 8080
    servlet:
      context-path: /ins
spring:
    profiles: prod
datasource:
    sampleapp:
        url: jdbc:mysql://localhost:3306/gastos
        username: root
        password: 106Galatea
        driverClassName: com.mysql.jdbc.Driver
        defaultSchema:
        maxPoolSize: 20
        hibernate:
            hbm2ddl.method: update
            show_sql: true
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect